version: "1"
services:
  - type: web
    name: internship-project
    runtime: node
    repo: https://github.com/Kittu-2006/internship-project
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        sync: false
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
